import course

COURSES = [
    course.Course(period=1,
                  name='Intro to Computer Science',
                  teacher_name='Ms. Lee',
                  resource_name='repl.it',
                  resource_url='https://repl.it/'),
    course.Course(period=2,
                  name='Video Art',
                  teacher_name='Mr. Boyd',
                  resource_name='Final Cut Pro',
                  resource_url='https://www.apple.com/final-cut-pro/'),
    course.Course(period=3,
                  name='Precalculus',
                  teacher_name='Mrs. Chand',
                  resource_name='Khan Academy',
                  resource_url='https://www.khanacademy.org/math/precalculus'),
    course.Course(period=4,
                  name='Government',
                  teacher_name='Mr. Capitan',
                  resource_name='Wikipedia',
                  resource_url='https://en.wikipedia.org/wiki/Federal_government_of_the_United_States'),
    course.Course(period=5,
                  name='Advanced digital photo',
                  teacher_name='Mr. Boyd',
                  resource_name='Photoshop',
                  resource_url='https://www.adobe.com/products/photoshop.html?sdid=KKQIN&mv=search&s_kwcid=AL!3085!3!226997989086!e!!g!!photoshop&ef_id=Wn-NKAAAAISGeBOf:20180419160441:s'),
    course.Course(period=6,
                  name='ERWC',
                  teacher_name='Mrs. Wenzell',
                  resource_name='CSU',
                  resource_url='https://writing.csusuccess.org/'),
]
